name: Build and deploy app (manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          output_location: 'build'
          app_build_command: 'npm run build'
        env:
          PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
